# Generated by Django 3.2.7 on 2021-09-20 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210920_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9409a26e-1649-42f3-8f9c-339476a9188e'), primary_key=True, serialize=False, unique=True),
        ),
    ]
