# Generated by Django 3.2.7 on 2021-09-20 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55742452-e07b-446f-bf47-f8139481ac56'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
