# Generated by Django 3.2.7 on 2021-10-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='facebook_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='instagram_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='twitter_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='youtube_url',
            field=models.URLField(null=True),
        ),
    ]
