# Generated by Django 3.2.7 on 2021-09-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210921_0538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='destinationcity',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='destinationcountry',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='destinationcountry',
            name='country_image',
            field=models.ImageField(default='img/default.jpg', upload_to='media/country/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='img/default.jpg', upload_to='media/featured_images'),
        ),
    ]
