# Generated by Django 3.2.7 on 2021-09-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210921_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationcountry',
            name='country_image',
            field=models.ImageField(default='static/img/default.jpg', upload_to='media/country/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(upload_to='media/featured_images'),
        ),
    ]
