# Generated by Django 3.2.7 on 2021-09-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210921_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('country_image', models.ImageField(upload_to='media/country/images')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.DeleteModel(
            name='DestinationCity',
        ),
        migrations.DeleteModel(
            name='DestinationCountry',
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ManyToManyField(blank=True, to='blog.Destination'),
        ),
    ]
