# Generated by Django 3.2.7 on 2021-10-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211002_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile_picture',
            field=models.ImageField(upload_to='images/profile-pictures/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(upload_to='images/featured-images/'),
        ),
    ]
