# Generated by Django 3.2.7 on 2021-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210922_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
