# Generated by Django 3.2.7 on 2021-09-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
