# Generated by Django 3.2.7 on 2021-09-22 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('destination_image', models.ImageField(upload_to='destination')),
                ('slug', models.SlugField(unique=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='destination.Category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.country')),
            ],
        ),
    ]
