# Generated by Django 3.2.7 on 2021-10-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_remove_destination_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='destination_image',
            field=models.ImageField(upload_to='images/destination-images/'),
        ),
    ]
