# Generated by Django 3.2.7 on 2021-09-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='destination',
        ),
    ]
